### ISSUE TITLE
Update theme configuration

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#22]
Make sure:

- [x] `theme.toml` [is complete](https://github.com/gohugoio/hugoThemesSiteBuilder/blob/main/README.md#theme-configuration)
  - [x] name
  - [x] license
  - [x] licenselink
  - [x] description
  - [x] homepage
  - [x] demosite (if one exists)
  - [x] tags
  - [x] features
  - [x] authors/author (depending on whether the theme has multiple or a single author)
  - [x] original (if the theme is a fork)
  - [x] remove `min_version`
- [x] `config.toml` file is present

    ```toml
    [module]
      [module.hugoVersion]
        extended = true
        min = "0.146.0"
    ```
