### ISSUE TITLE
Add count to taxonomies

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#32]
## Code Example

Change `layouts/taxonomy.html`:

```go
{{ $taxonomy := index .Site.Taxonomies .Data.Plural }}
<h1>{{ .Title }}</h1>
{{- with .Pages }}
<ul>
  {{ range . -}}
  <li>{{ .Title }} <span class="count">{{ $taxonomy.Count .Data.Term }}</span></li>
  {{- end }}
</ul>
{{ end }}
```

Add CSS style:

```css
.count:before {
    content: "(";
}

.count:after {
    content: ")";
}
```

## Example Generated Code

```html
<h1>Categories</h1>
<ul>
  <li>Example1 <span class="count">5</span></li>
  <li>Example2 <span class="count">5</span></li>
</ul>
```

## Example visual representation:

---

### Categories

- Example1 (5)
- Example2 (3)

---
