### ISSUE TITLE
Improve theme switcher code

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#36]
# Theme Switcher

## To Do

- [ ] Change `.theme-switcher button` to `[data-function="switch-color-scheme"]`
- [ ] Add `data-*` to theme switcher button
- [ ] Add CSS styles for `[data-symbol]`
- [ ] Remove theme switcher assets from `assets/css/assets.gtpl.css`
- [ ] Change theme switcher button selector for `ManageColorScheme`

## Some of the required code changes

Modify theme switcher button in `layouts/_partials/menu.html`.

```html
<button
  type="button"
  data-symbol
  data-function="switch-color-scheme"
  aria-label="Theme Switch"
></button>
```

Modify CSS for theme switcher button in `css/sine-die/theme-switcher/styles.css`.

```css
[data-symbol] {
  font-family: 'Material Symbols Outlined';
  display: inline-block;
}

li:has([data-function="switch-color-scheme"]) {
  width: 3em;
  align-content: center;
}

[data-function="switch-color-scheme"] {
  background-color: transparent;
  border: none;
  cursor: pointer;
  height: 90%;
  margin: 0;
  padding: 0;
  aspect-ratio: 1/1;
}

[data-function="switch-color-scheme"]::before {
  content: "contrast";
}

[data-color-scheme="dark"] [data-function="switch-color-scheme"]::before {
  content: "dark_mode";
}

[data-color-scheme="light"] [data-function="switch-color-scheme"]::before {
  content: "light_mode";
}

[data-function="switch-color-scheme"]:enabled:hover {
  background-color: var(--color-tertiary);
  color: var(--color-on-tertiary);
  font-size: 150%;
}

@media only screen and (width <= 1024px) {
  li:has([data-function="switch-color-scheme"]) {
    text-align: center;
  }

  [data-function="switch-color-scheme"] {
    display: inline-block;
    min-height: 2.5rem;
    aspect-ratio: auto;
  }
}
```
