### ISSUE TITLE
Improve menubar

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#37]
## To Do

> [!TIP]
> Do after #29 and #36

- [ ] Remove use of `responsive` CSS class
- [ ] Change use of `menu-icon` CSS class to `data-function="mobile-menu"`
- [ ] Add `aria-haspopup="menu"` and `aria-expanded="false"` to mobile menu button
- [ ] Change mobile menu button `aria-label` when switching between open/close menu
- [ ] Move mobile menu button js code in `assets/js/sine-die/menubar.js`
- [ ] Use material symbols for arrows in submenu buttons
- [ ] Change submenu buttons `aria-label` when switching between open/close menu

## Some of the required code changes

Modify mobile button in `layouts/_partials/header.html`.

```html
<button
  type="button"
  data-symbol
  data-function="mobile-menu"
  aria-haspopup="menu"
  aria-expanded="false"
  aria-label="Show Menu"
  aria-controls="menu"
></button>
```

Merge the following `MobileMenu` code with `MenubarNavigation` in `assets/js/theme/menubar.js`

```js
class MobileMenu {
  #button;
  #openLabel;
  #closeLabel;
  constructor(button, openLabel = 'Open main menu', closeLabel = 'Close main menu') {
    this.#button = button;
    this.#openLabel = openLabel;
    this.#closeLabel = closeLabel;
    this.#button.addEventListener("click", this.switchMenu.bind(this));
    this.updateMenu(this.isExpanded);
  }

  get isExpanded() {
    return this.#button.getAttribute("aria-expanded") === 'true';
  }

  updateMenu(expanded) {
    let label = expanded ? this.#closeLabel : this.#openLabel;
    this.#button.setAttribute("aria-label", label);
    this.#button.setAttribute("aria-expanded", expanded.toString());
  }

  switchMenu() {
    let toggleExpanded = !(this.isExpanded);
    this.updateMenu(toggleExpanded);
  }
}

const mobileMenuButton = document.querySelector(".menu-icon");
new MobileMenu(mobileMenuButton);
```

In `assets/css/menubar/style.css`

```css
[data-function="mobile-menu"] {
  font-size: 1.2em;
  position: absolute;
  right: .2em;
  top: .2em;
  font-size: 2em;
  aspect-ratio: 1 / 1;
  border: none;
}

[data-function="mobile-menu"]::before {
  font-size: 1.2em;
}

[data-function="mobile-menu"][aria-expanded="false"]::before {
  content: "menu";
}

[data-function="mobile-menu"][aria-expanded="true"]::before {
  content: "close";
}

nav.primary [role="menubar"] li:has(> [aria-haspopup="true"]) {
  display: grid;
  grid-template:
      "link button" auto
      "menu menu" auto
      / 1fr auto;
  align-content: center;
}

[role="menubar"] button[aria-expanded] {
  aspect-ratio: 1/1;
  background-color: transparent;
  font-size: 1.5em;
  border: none;
  cursor: pointer;
  height: 2em;
  margin: 0;
  padding: 0;
}

[role="menubar"] button[aria-expanded]:enabled:hover::before {
  color: var(--color-on-tertiary);
  font-size: 150%;
}

[role="menubar"] button[aria-expanded="false"]::before {
  content: "arrow_drop_down";
}

[role="menubar"] button[aria-expanded="true"]::before {
  content: "arrow_drop_up";
}
nav.primary [role="menubar"] li:has(> [aria-haspopup="true"]) > a {
  grid-area: link;
}

nav.primary [role="menubar"] li:has(> [aria-haspopup="true"]) > button {
  grid-area: button;
}

nav.primary [role="menubar"] li:has(> [aria-haspopup="true"]) > ul {
  grid-area: menu;
}

@media only screen and (width <= 1024px) {
  nav.primary [role="menubar"] ul,
  nav.primary [role="menubar"] li {
    margin-right: 0;
    padding-right: 0;
  }

  nav.primary [role="menubar"] li > a {
    display: inline-block;
    min-height: 2.5rem;
  }

  nav.primary [role="menubar"] li > button {
    min-width: 3.5rem;
  }

  nav.primary [role="menubar"] li:has([aria-expanded="true"]) ul,
  nav.primary [role="menubar"] li:has([aria-expanded="true"]) {
    padding-bottom: 0;
  }

  nav.primary [role="menubar"]:has(+ [aria-expanded="false"]) {
    display: none;
  }
}

@media only screen and (width > 1024px) {
  [data-function="mobile-menu"] {
    display: none;
  }
}
```
