### ISSUE TITLE
Generate and use Light/Dark mode for chroma code highlight

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#38]
## To Do

- Use [Dart Sass](https://gohugo.io/functions/css/sass/#dart-sass) (and update GitHub workflow)
- [Generate chroma styles](#generate-chroma-styles) for Light/Dark mode
- [Create code highlight SCSS file](#create-code-highlight-scss-file) `css/sine-die/code-highlight/style.scss`
- [Use code highlight SCSS file as CSS resource](#use-code-highlight-scss-file-as-css-resource)
- [Configure markup highlight](#configure-markup-highlight)

### <a id="generate-chroma-styles" /> Generate chroma styles

```sh
highlight_css_dir=assets/sine-die/css/code-highlight
highlight_style_light=catppuccin-latte
highlight_style_dark=catppuccin-frappe
hugo gen chromastyles --style="${highlight_style_light:?}" > "${highlight_css_dir:?}/_light.css"
hugo gen chromastyles --style="${highlight_style_dark:?}" > "${highlight_css_dir:?}/_dark.css"
```

### <a id="create-code-highlight-scss-file" /> Create code highlight SCSS file

Create `sine-die/css/code-highlight/style.scss` file

```scss
// code-highlight/style.scss
@use "sass:meta";

@mixin theme-color-scheme($name) {
  @include meta.load-css($name);
  .chroma {
    background-color: var(--color-surface-container-high);
  }
}

/* Light Theme */
[data-color-scheme="light"] {
  @include theme-color-scheme("light");
}

@media (prefers-color-scheme: light) {
  :root:not([data-color-scheme="light"], [data-color-scheme="dark"]),
  [data-color-scheme="default"] {
    @include theme-color-scheme("light");
  }
}

/* Dark Theme */
[data-color-scheme="dark"] {
  @include theme-color-scheme("dark");
}

@media (prefers-color-scheme: dark) {
  :root:not([data-color-scheme="light"], [data-color-scheme="dark"]),
  [data-color-scheme="default"] {
    @include theme-color-scheme("dark");
  }
}
```

### <a id="use-code-highlight-scss-file-as-css-resource" /> Use code highlight SCSS file as CSS resource

Add `code-highlight/style.scss` to `$assets` slice in `layouts/_partials/head/css.html`

### <a id="configure-markup-highlight" /> Configure markup highlight

Modify `userguide/hugo.toml`

```toml
[markup]
  [markup.highlight]
    noClasses = false
```
