### ISSUE TITLE
Add copy button to code block

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#39]
See https://github.com/alex-shpak/hugo-book/issues/616 and https://aaronluna.dev/blog/add-copy-button-to-code-blocks-hugo-chroma/  for examples.

Use `content_copy` icon from  [Material Symbols](https://developers.google.com/fonts/docs/material_symbols).

CSS example:

```css
[data-symbol] {
  font-family: 'Material Symbols Outlined';
}

.highlight  {
  position: relative;
}

.highlight button {
  position: absolute;
  right: .5em;
  top: .5em;
}
```

Javascript example:

```js
class CodeBlockCopyButton {
  #preCodeBlock
  constructor(preCodeBlock, label = 'Copy', icon = 'content_copy') {
    let button = document.createElement('button');
    button.setAttribute('aria-label', label);
    button.setAttribute('data-symbol', true);
    button.textContent = icon;
    button.addEventListener("click", this.copyCode.bind(this));
    preCodeBlock.parentNode.insertBefore(button, preCodeBlock);
    this.#preCodeBlock = preCodeBlock;
  }

  copyCode() {
    let codeText = this.#preCodeBlock.querySelector("code[data-lang]").textContent;
    navigator.clipboard.writeText(codeText);
  }
}

window.addEventListener('load', function () {
  var preCodeBlocks = document.querySelectorAll('.highlight pre:has(code[data-lang])');
  for (var i = 0; i < preCodeBlocks.length; i++) {
    new CodeBlockCopyButton(preCodeBlocks[i]);
  }
});
```
