### ISSUE TITLE
Fix copy code highlight

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#65]
To Do

- [x] rename `assets/sine-die/js/code-highlight.js` to `assets/sine-die/js/code-highlight-copy.js`
- [x] use line numbers for code highlight block
    ```toml
    [markup]
      [markup.highlight]
        noClasses = false
        lineNos = true
        lineNumbersInTable = false
    ```
- [x] modify copy button javascript class
    ```js
      getCodeText() {
        let codeBlock = this.#preCodeBlock.querySelector("code[data-lang]");
        let codeLines = codeBlock.querySelectorAll(".line > .cl");
        let codeText = Array.from(codeLines, (elem) => elem.textContent).join("");
        return codeText;
      }
    ```
- [x] modify copy button height and border-radius in CSS
    ```css
    .highlight button {
      border-radius: 25%;
      font-size: 1em;
      height: 2em;
      position: absolute;
      right: .5em;
      top: .5em;
    }
- [x] hide copy button in media print CSS
    ```css
    .highlight button {
      display: none;
    }
    ```
