### ISSUE TITLE
Hide clear button in empty search for assistive technologies

### ISSUE THREAD

**Issue by sinetris** [sinetris/sine-die#66]
The clear button in the search bar should not be focusable when the search bar is empty.

```css
#search button.pagefind-ui__search-clear.pagefind-ui__suppressed {
  display: none;
}
```
